import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Blog from '../components/Blog';

const URL = process.env.NEXT_PUBLIC_STRAPI_API_URL;

export async function getStaticProps(context) {
  const fetchParams = {
    method: "POST",
    headers: {
      "content-type": "application/json"
    },
    body: JSON.stringify({
      query: `{
      posts {
        data {
          attributes {
            title
            body
            description
            slug
            publishedAt
          }
        }
      }
    }`
    })
  }

  const res = await fetch(`${URL}/graphql`, fetchParams);
  const data = await res.json();

  return {
    props: data,
  };
}

export default function Home({ data }) {
  console.log(data);
  const posts = data.posts.data;
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          9d8.dev
        </h1>

        <div className={styles.grid}>
          {posts.map((post, index) => {
            const { title, description, slug } = post.attributes;
            return (
              <Blog key={index} title={title} description={description} slug={slug}/> 
            )
          })}
        </div>
      </main>
    </div>
  )
}
